### ISSUE TITLE
`misaligned pointer dereference` error in `PacketListIterator::next`

### ISSUE THREAD

**Issue by arteme** [chris-zen/coremidi#49] opened 2024-01-16 10:32 UTC
Hi,

In [pod-ui](https://github.com/arteme/pod-ui) I'm using `coremidi` through `midir`. I have a badly-behaving M-Vave MS-1 bluetooth MIDI device that keeps crashing the app. I know, `midir` 0.9.x uses an old version of `coremidi`,  I've tried  https://github.com/Boddlnagg/midir/pull/139 and https://github.com/Boddlnagg/midir/pull/142, but the error still prevails.

I understand that MS-1 is the culprit here, but is there some sanity-checking in `PacketListIterator` that can be done to prevent crashing? 

Here are the backtraces:
[coremidi-panic-midir0.9.1.txt](https://github.com/chris-zen/coremidi/files/13948646/coremidi-panic-midir0.9.1.txt)
[coremidi-panic-midir0.9.2+coremidi0.7.0.txt](https://github.com/chris-zen/coremidi/files/13948648/coremidi-panic-midir0.9.2%2Bcoremidi0.7.0.txt)
[coremidi-panic-midir0.9.2+coremidi0.8.0.txt](https://github.com/chris-zen/coremidi/files/13948649/coremidi-panic-midir0.9.2%2Bcoremidi0.8.0.txt)

**Comment by jmbarbier** [comment] 2024-04-28 23:40
Same bug here, fixed it by adding `read_unaligned` for those lines

```rs
#[inline]
pub unsafe fn MIDIPacketNext(pkt: *const MIDIPacket) -> *const MIDIPacket {
    // Get pointer to potentially unaligned data without triggering undefined behavior
    // addr_of does not require creating an intermediate reference to unaligned data.
    let ptrx = ptr::addr_of!((*pkt).data) as *const u8;
    let rawl = ptr::addr_of!((*pkt).length) as *const u16;
    let offset = rawl.read_unaligned() as isize;
    if cfg!(any(target_arch = "arm", target_arch = "aarch64")) {
        // MIDIPacket must be 4-byte aligned on ARM
        ((ptrx.offset(offset + 3) as usize) & !(3usize)) as *const MIDIPacket
    } else {
        ptrx.offset(offset) as *const MIDIPacket
    }
}

#[inline]
pub unsafe fn MIDIEventPacketNext(pkt: *const MIDIEventPacket) -> *const MIDIEventPacket {
    // Get pointer to potentially unaligned data without triggering undefined behavi
    // or
    // addr_of does not require creating an intermediate reference to unaligned data.
    let ptrx = ptr::addr_of!((*pkt).words) as *const u8;
    let rawwc = ptr::addr_of!((*pkt).wordCount) as *const u32;
    let wc = rawwc.read_unaligned() as usize;
    let offset = (wc * mem::size_of::<u32>()) as isize;
    if cfg!(any(target_arch = "arm", target_arch = "aarch64")) {
        // MIDIEventPacket must be 4-byte aligned on ARM
        ((ptrx.offset(offset + 3) as usize) & !(3usize)) as *const MIDIEventPacket
    } else {
        ptrx.offset(offset) as *const MIDIEventPacket
    }
}
```

Take this as a hack without any warranty ("it works for me"), i have no knowledge of the internals used here...

**Comment by Boddlnagg** [comment] 2024-05-09 14:19
This has repeatedly hit users of `midir`. I think the proposed fix by @jmbarbier is correct, but that code is actually part of https://github.com/jonas-k/coremidi-sys.
@jmbarbier Maybe you can open a PR against coremidi-sys?

**Comment by Boddlnagg** [comment] 2024-05-09 14:34
Actually I'm not sure whether that fix is correct. `MIDIPacket` should be 4-byte aligned on ARM (see also https://github.com/chris-zen/coremidi/pull/9), so `read_unaligned` shouldn't be necessary. The error must be somewhere else where `MIDIPacket`s are constructed that are not aligned.

**Comment by Boddlnagg** [comment] 2024-05-09 14:55
Okay, I think the problem is this: "The alignment requirements of MIDIPacket may differ between CPU architectures. On Intel and PowerPC, MIDIPacket is unaligned. On ARM, MIDIPacket must be 4-byte aligned."
(https://github.com/phracker/MacOSX-SDKs/blob/041600eda65c6a668f66cb7d56b7d1da3e8bcc93/MacOSX10.15.sdk/System/Library/Frameworks/CoreMIDI.framework/Versions/A/Headers/MIDIServices.h#L420-L423)

So I'm assuming that this issue occurs on Intel processors? That would make sense because then Rust sees an unaligned `MIDIPacket` that should be 4-byte aligned but isn't, so the `read_unaligned` is needed to not trigger Rust's UB check. On ARM this would not be needed and would actually make performance worse, because on ARM the packets *are* aligned and explicit unaligned reads would generate worse machine code.

Furthermore, this can only affect `MIDIPacket`, not `MIDIEvent` (its length will always be a multiple of 4 bytes), so the fix does not need to be applied to `MIDIEventPacketNext`.

**Comment by Boddlnagg** [comment] 2024-05-09 15:11
@jmbarbier @arteme @oilcake Can you confirm that you're seeing this on Intel processors?

**Comment by oilcake** [comment] 2024-05-09 15:24
> @jmbarbier @arteme @oilcake Can you confirm that you're seeing this on Intel processors?

Yep, my one is intel.

**Comment by Boddlnagg** [comment] 2024-06-11 11:49
This should be fixed with the latest version of `coremidi-sys`

**Comment by oilcake** [comment] 2024-06-11 13:02
> This should be fixed with the latest version of `coremidi-sys`

Just checked - still panicking on my side with the same error :( 
Project was recompiled with coremidi-sys==0.8.0 which I believe is the latest.

**Comment by arteme** [comment] 2024-06-11 13:34
I think, @Boddlnagg  means coremidi-sys version 3.1.1 released a couple hours ago.

Unfortunately I no longer have my MS-1 device to check with, so I can be of little help.

**Comment by Boddlnagg** [comment] 2024-06-12 08:46
> I think, @Boddlnagg means coremidi-sys version 3.1.1 released a couple hours ago.

Yes, that's right

**Comment by oilcake** [comment] 2024-06-12 10:17
Oh, sorry, I did recheck project's dependencies and found coremidi-sys v3.1.0. Will try to update and recompile once again.

**Comment by oilcake** [comment] 2024-06-20 10:26
> > I think, @Boddlnagg means coremidi-sys version 3.1.1 released a couple hours ago.
> 
> Yes, that's right

Sorry, did not get it.

**Comment by Boddlnagg** [comment] 2024-06-26 18:23
@oilcake So does that mean that it works now?

**Comment by oilcake** [comment] 2024-06-27 16:16
> @oilcake So does that mean that it works now?

Sorry, I just did not still figure out how to check - when I do `cargo tree` cargo tells me that my project depends on `midir v0.10.0`, which is as I can see is the latest, and it depends on `coremidi v3.1.0`. Should I try to fork midir and set 3.1.1 in midir's `Cargo.toml`?

**Comment by Boddlnagg** [comment] 2024-06-27 17:12
Since neither `midir` nor `coremidi` lock to a specific version, `cargo update` should be able to update to the latest (compatible) version.
And indeed when I do `cargo update` I see:
```
Updating coremidi-sys v3.1.0 -> v3.1.1
```
If that doesn't work, you can try
```
cargo update --precise 3.1.1 coremidi-sys
```

**Comment by oilcake** [comment] 2024-06-27 17:23
> Since neither `midir` nor `coremidi` lock to a specific version, `cargo update` should be able to update to the latest (compatible) version. 
> 

Thank you so much! I am new to rust and did not know cargo can do such a thing.
It works after `cargo update`! 👍

**Comment by Boddlnagg** [comment] 2024-06-29 12:57
@chris-zen Maybe you can increase the version requirement of `coremidi-sys` for the next release, so everybody gets the fix then.

**Closed as completed** 2024-06-30 07:39 UTC

**Comment by oilcake** [comment] 2025-09-13 18:17
HI!
I've recently got the exact same bug with `midir v0.10.2` and `coremidi-sys v3.2.0`. Can it be fixed like the first one?

**Comment by Boddlnagg** [comment] 2025-09-16 17:19
@oilcake Can you provide a backtrace? And can you confirm that you're also on an Intel processor?

The original issue can't really occur anymore, because it's now a `read_unaligned` call, which should never result in a `misaligned pointer dereference` error.

For reference, the fix of the original issue was done in https://github.com/jonas-k/coremidi-sys/pull/18.

**Comment by oilcake** [comment] 2025-09-18 09:45
> [@oilcake](https://github.com/oilcake) Can you provide a backtrace? And can you confirm that you're also on an Intel processor?

Yes, I am on Intel, and yes, of course:
```
thread '<unnamed>' panicked at /Users/oilcake/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/coremidi-0.8.0/src/packets.rs:91:35:
misaligned pointer dereference: address must be a multiple of 0x4 but is 0x70000ecf2f41
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/panicking.rs:117:22
   2: core::panicking::panic_nounwind_fmt
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/intrinsics/mod.rs:2340:9
   3: core::panicking::panic_misaligned_pointer_dereference
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/panicking.rs:293:5
   4: <coremidi::packets::PacketListIterator as core::iter::traits::iterator::Iterator>::next
             at /Users/oilcake/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/coremidi-0.8.0/src/packets.rs:91:35
   5: midir::backend::coremidi::MidiInput::handle_input
             at /Users/oilcake/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/midir-0.10.2/src/backend/coremidi/mod.rs:89:18
   6: midir::backend::coremidi::MidiInput::connect::{{closure}}
             at /Users/oilcake/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/midir-0.10.2/src/backend/coremidi/mod.rs:208:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread caused non-unwinding panic. aborting.
```
Sorry for the delay
